### ISSUE TITLE
No ids for headers

### ISSUE THREAD

**Issue by geekyogurt** [singingwolfboy/flask-misaka#26]
Flask Misaka, unlike jekyll  and python markdown library doesnot add id to headings.

**Comment by singingwolfboy** [comment]
This sounds like an issue for [Misaka](https://misaka.61924.nl/), not this project.

**Comment by geekyogurt** [comment]
How to set nesting level Flask-Misaka? Misaka provides this as a option in Rendererer
class misaka.HtmlRenderer(flags=0, nesting_level=0)

**Comment by singingwolfboy** [comment]
You can set a custom renderer in the [`flask_misaka.markdown()`](https://flask-misaka.readthedocs.io/en/latest/#flask_misaka.markdown) function, or in the [`flask_misaka.Misaka` constructor](https://flask-misaka.readthedocs.io/en/latest/#flask_misaka.Misaka.__init__). You can import the `HtmlRenderer` class from `misaka` and use that.

In the future, please open a new issue for unrelated problems. I'm going to close this issue, since the "adding ids to headings" question is resolved.
